version: "3.9"
${{ secrets.REOLINK_PASSWORD }}
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    restart: unless-stopped
    shm_size: "64mb"
    ports:
      - "8971:8971"
      - "8554:8554"       # RTSP restreams
      - "8555:8555/tcp"   # WebRTC over TCP
      - "8555:8555/udp"   # WebRTC over UDP
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /media/frigate:/media/frigate
    environment:
      - FRIGATE_RTSP_PASSWORD=supersecret