mqtt:
  enabled: false

  
ui:
  live_mode: go2rtc

go2rtc:
  streams:
    doorbell_main:
      - "ffmpeg:rtsp://admin:{REOLINK_PASSWORD}@192.168.50.215:554/h264Preview_01_main#an"
    doorbell_sub:
      - "ffmpeg:rtsp://admin:{REOLINK_PASSWORD}@192.168.50.215:554/h264Preview_01_sub#an"

cameras:
  doorbell:
    live:
      stream_name: doorbell_main
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          roles:
            - detect
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 1
        mode: all
