mqtt:
  enabled: false

go2rtc:
  streams:
    doorbell:
      - "rtsp://admin:{REOLINK_PASSWORD}@192.168.50.215:554/h264Preview_01_main"

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
