mqtt:
  enabled: false

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{REOLINK_PASSWORD}@192.168.50.215:554/Preview_01_main
          roles:
            - record
        - path: rtsp://admin:{REOLINK_PASSWORD}@192.168.50.215:554/Preview_01_sub
          roles:
            - detect
    detect:
      enabled: false
      width: 1280
      height: 720

version: 0.15-1