mqtt:
  enabled: false

  
ui:
  live_mode: record

go2rtc:
  streams:
    doorbell_main:
      - "rtsp://admin:{REOLINK_PASSWORD}@192.168.50.215:554/h264Preview_01_main"
    doorbell_sub:
      - "rtsp://admin:{REOLINK_PASSWORD}@192.168.50.215:554/h264Preview_01_sub"

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          roles:
            - detect
