mqtt:
  enabled: false

go2rtc:
  streams:
    your_reolink_doorbell:
      - "ffmpeg:http://192.168.50.215/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=gooddeal#1#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.50.215/Preview_01_sub

cameras:
  name_of_your_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/your_reolink_camera
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
version: 0.15-1
